//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFIlmaProjekat.ServiceGradFilma {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGradFilma.IGradFilmaService")]
    public interface IGradFilmaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Login", ReplyAction="http://tempuri.org/IGradFilmaService/LoginResponse")]
        GradFilmaModel.Korisnik Login(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Login", ReplyAction="http://tempuri.org/IGradFilmaService/LoginResponse")]
        System.Threading.Tasks.Task<GradFilmaModel.Korisnik> LoginAsync(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Register", ReplyAction="http://tempuri.org/IGradFilmaService/RegisterResponse")]
        void Register(GradFilmaModel.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradFilmaService/Register", ReplyAction="http://tempuri.org/IGradFilmaService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(GradFilmaModel.Korisnik korisnik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGradFilmaServiceChannel : GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GradFilmaServiceClient : System.ServiceModel.ClientBase<GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService>, GradFIlmaProjekat.ServiceGradFilma.IGradFilmaService {
        
        public GradFilmaServiceClient() {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradFilmaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradFilmaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GradFilmaModel.Korisnik Login(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.Login(korisnik);
        }
        
        public System.Threading.Tasks.Task<GradFilmaModel.Korisnik> LoginAsync(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.LoginAsync(korisnik);
        }
        
        public void Register(GradFilmaModel.Korisnik korisnik) {
            base.Channel.Register(korisnik);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(GradFilmaModel.Korisnik korisnik) {
            return base.Channel.RegisterAsync(korisnik);
        }
    }
}
