//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Projekcijas = new HashSet<Projekcija>();
        }
    
        public int idFilm { get; set; }
        public string naziv { get; set; }
        public string reziser { get; set; }
        public string glumci { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Projekcija> Projekcijas { get; set; }
    }
}
