//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GradFilmaEntities : DbContext
    {
        public GradFilmaEntities()
            : base("name=GradFilmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<KinoSala> KinoSalas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Privilegije> Privilegijes { get; set; }
        public virtual DbSet<Projekcija> Projekcijas { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<SpecijalnePonude> SpecijalnePonudes { get; set; }
        public virtual DbSet<StavkePrivilegije> StavkePrivilegijes { get; set; }
        public virtual DbSet<TipMjesta> TipMjestas { get; set; }
        public virtual DbSet<TipProjekcije> TipProjekcijes { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
        public virtual DbSet<Uposlenik> Uposleniks { get; set; }
    }
}
