//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int idKarta { get; set; }
        public int RezervacijaId { get; set; }
        public string barkod { get; set; }
    
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
