//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilegije
    {
        public Privilegije()
        {
            this.StavkePrivilegijes = new HashSet<StavkePrivilegije>();
        }
    
        public int idPrivilegije { get; set; }
        public int ulogaId { get; set; }
        public Nullable<int> manipulacijaKorisnicima { get; set; }
        public Nullable<int> manipulacijaPodacima { get; set; }
        public Nullable<int> manipulacijaRezervacijama { get; set; }
        public Nullable<int> manipulacijaSadrzajem { get; set; }
        public Nullable<int> manipulacijaUposlenicima { get; set; }
        public Nullable<int> registracija { get; set; }
    
        public virtual Uloga Uloga { get; set; }
        public virtual ICollection<StavkePrivilegije> StavkePrivilegijes { get; set; }
    }
}
