//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekcija
    {
        public Projekcija()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int idProjekcija { get; set; }
        public System.DateTime vrijemePrikazivanja { get; set; }
        public int tipProjekcijeId { get; set; }
        public int filmId { get; set; }
        public int kinoSalaId { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual KinoSala KinoSala { get; set; }
        public virtual TipProjekcije TipProjekcije { get; set; }
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
