//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradFilmaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipProjekcije
    {
        public TipProjekcije()
        {
            this.Projekcijas = new HashSet<Projekcija>();
        }
    
        public int idTipProjekcije { get; set; }
        public Nullable<int> C2D { get; set; }
        public Nullable<int> C3D { get; set; }
        public Nullable<int> C4D { get; set; }
    
        public virtual ICollection<Projekcija> Projekcijas { get; set; }
    }
}
